<p>Vítejte v administraci, jste přihlášeni jako <?= $jmeno ?></p>
<?php if (!$admin) : ?>
	<p>Nemáte administrátorská oprávnění, požádejte administrátora webu, aby vám je přidělil.</p>
<?php endif ?>
<h2><a href="editor">Editor článků</a></h2>
<h2><a href="clanek">Seznam článků</a></h2>
<h2><a href="sablony">Nahrát šablony</a></h2>
<h2><a href="uzivatele">Správa uživatelů</a></h2>
<h2><a href="objednavky">Správa objednávek</a></h2>
<h2><a href="/odhlasit">Odhlásit</a></h2>
