<h1>Objednávka vizitek</h1>
<form id="businessCardForm" action="mailer_objednavka.php">
    <div class="form-group">
        <label for="quantity">Počet vizitek:</label>
        <input type="number" min="0" step="0,1" id="quantity" name="quantity" placeholder="Zadejte počet vizitek" required>
    </div>

    <div class="form-group">
        <label for="paperType">Druh papíru:</label>
        <select id="paperType" name="paperType" required>
            <?php foreach ($this->paperTypes as $paperType): ?>
                <option value="<?= $paperType['idpaper_type'] ?>"><?= $paperType['name'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="printType">Tisk:</label>
        <select id="printType" name="printType" required>
            <?php foreach ($this->printTypes as $printType): ?>
                <option value="<?= $printType['idprint'] ?>"><?= $printType['name'] ?></option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="measurement">Rozměr:</label>
        <select id="measurement" name="measurement" required>
            <?php foreach ($this->measurements as $measurement): ?>
                <option value="<?= $measurement['idmeasurement'] ?>"><?= $measurement['name'] ?> - <?= $measurement['price'] ?> Kč</option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group">
        <label for="template">Vyberte šablonu:</label>
        <select id="template" name="template" required>
            <?php foreach ($this->cardTemplates as $template): ?>
                <option value="<?= $template['idcard_template'] ?>" data-image="<?= $template['picture'] ?>">
                    <?= $template['name'] ?>
                </option>
            <?php endforeach; ?>
        </select>
    </div>

    <div class="form-group" id="templatePreview" style="display: none;">
        <label for="templatePreviewImage">Mini náhled šablony:</label>
        <img id="templatePreviewImage" src="" alt="Mini náhled šablony" width="100">
    </div>

    <div class="price">
        Cena: <span id="price">0 Kč</span>
    </div>

    <button id="orderButton" type="submit" class="btn">Objednat</button>
</form>

<script src="js/nahledy.js">
</script>