<form method="post" action="registrace">
	<label>
		Jméno<br />
		<input type="text" name="jmeno" />
	</label><br />
	<label>
		E-Mail<br />
		<input type="text" name="email" />
	</label><br />
	<label>
		Heslo<br />
		<input type="password" name="heslo" />
	</label><br />
	<label>
		Heslo znovu<br />
		<input type="password" name="heslo_znovu" />
	</label><br />
	<label>
		Zadejte aktuální rok (antispam)<br />
		<input type="text" name="rok" />
	</label><br />
	<input type="submit" value="Registrovat" />
</form>